// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCofcD3fDn8uqYew7LVGBYBv1bAFhYBu30',
    appId: '1:709333701369:web:3e0711c34d44f1597f8828',
    messagingSenderId: '709333701369',
    projectId: 'hytide-crm',
    authDomain: 'hytide-crm.firebaseapp.com',
    storageBucket: 'hytide-crm.firebasestorage.app',
    measurementId: 'G-PH4N1QH17F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR94gzAU83xQw095uOUf-eVkqvQbmKEjQ',
    appId: '1:709333701369:android:851e1177d9bd0ea87f8828',
    messagingSenderId: '709333701369',
    projectId: 'hytide-crm',
    storageBucket: 'hytide-crm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4L4qDTAF_v5Jo8vMlxob4V3_e8wHiag8',
    appId: '1:709333701369:ios:c0fa978c54b548c77f8828',
    messagingSenderId: '709333701369',
    projectId: 'hytide-crm',
    storageBucket: 'hytide-crm.firebasestorage.app',
    iosBundleId: 'com.hytide.sale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4L4qDTAF_v5Jo8vMlxob4V3_e8wHiag8',
    appId: '1:709333701369:ios:c0fa978c54b548c77f8828',
    messagingSenderId: '709333701369',
    projectId: 'hytide-crm',
    storageBucket: 'hytide-crm.firebasestorage.app',
    iosBundleId: 'com.hytide.sale',
  );
}
