// lib/main.dart
//
// IMPORTANT: Before running, you must configure Firebase:
//   1. Create a Firebase project at https://console.firebase.google.com
//   2. Register Android (com.hytide.sale) and iOS (com.hytide.sale) apps
//   3. Run: npx -y firebase-tools login
//   4. Run: dart pub global activate flutterfire_cli
//   5. Run: flutterfire configure --project=YOUR_PROJECT_ID
//   This will generate lib/firebase_options.dart automatically.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'firebase_options.dart'; // Generated by: flutterfire configure
import 'core/routing/app_router.dart';
import 'core/theme/app_theme.dart';
import 'core/services/notification_service.dart';
import 'core/theme/theme_provider.dart';
import 'features/auth/repositories/auth_repository.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  await NotificationService().initialize();

  runApp(
    const ProviderScope(
      child: HytideApp(),
    ),
  );
}

class HytideApp extends ConsumerWidget {
  const HytideApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(routerProvider);
    final themeMode = ref.watch(themeModeProvider);

    // Synchronize FCM device token with auth lifecycle
    ref.listen(authStateProvider, (previous, next) {
      final prevUser = previous?.valueOrNull;
      final nextUser = next.valueOrNull;

      if (prevUser != null && nextUser == null) {
        // User signed out -> deactivate device token
        NotificationService().deactivateDevice(prevUser.uid);
      } else if (nextUser != null) {
        // User logged in -> register device token (Android only, Web safely skips)
        NotificationService().registerDeviceToken(nextUser.uid);
      }
    });

    // Check initial user state if already signed in on app start
    final initialUser = ref.watch(authStateProvider).valueOrNull;
    if (initialUser != null) {
      NotificationService().registerDeviceToken(initialUser.uid);
    }

    // Configure notification tap deep linking
    NotificationService().onNotificationRouteTapped = (route) {
      if (route.isNotEmpty) {
        router.push(route);
      }
    };
    NotificationService().onFollowUpNotificationTapped = (followUpId) {
      if (followUpId.isNotEmpty) {
        router.push('/followups/$followUpId');
      }
    };

    return MaterialApp.router(
      title: 'Hytide CRM',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: themeMode,
      routerConfig: router,
    );
  }
}
